#:schema node_modules/wrangler/config-schema.json
name = "viralcraftai"
main = "./build/server/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
send_metrics = false

[assets]
directory = "./build/client"
binding = "ASSETS"
